# Generated by Django 5.2 on 2025-04-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='is_excused',
            field=models.BooleanField(default=False),
        ),
    ]
